name: test

on:
  pull_request:
    branches: [main]

jobs:
  publish:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure .npmrc
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Perform basic audit
        run: npm audit --audit-level low

      - name: Install dependencies
        run: npm ci

      - name: Perform quality checks
        run: |
          npm run format:check
          npm run lint:check

      - name: Build from source and run tests
        run: |
          npm run build
          npm test
